name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: List and read file
          run: |
            echo "My first github actions"
            ls -ltr
            cat README.md