name: Multiple sequence jobs

on: workflow_dispatch

jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
      - name: write hello world
        run: echo "hello world" >> dummy.txt
  
      - name: upload dummy.txt
        uses: actions/upload-artifact@v3
        with:
          name: dummy-text-file
          path: dummy.txt
  
    approval:
      name: approval job
      needs: job1
      runs-on: ubuntu-latest
      environment:
        name: test
      steps:
        - uses: trstringer/manual-approval@v1
          with:
            secret: ${{ github.TOKEN }}
            approvers: ajaykaarthic
            minimum-approvals: 1
            issue-title: "Deploying v1.3.5 to prod from staging"
            issue-body: "Please approve or deny the deployment of version v1.3.5."
            exclude-workflow-initiator-as-approver: false
            additional-approved-words: ''
            additional-denied-words: ''